Traceback (most recent call last):
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print("Display Rows:",pd.get_option("display.max_rows"))
print("Display Columns:",pd.get_option("display.max_columns"))
print("Display Precision:",pd.get_option("precision"))
#pd.set_option("display.max_rows", 5)
#pd.set_option("display.max_columns", 5)
#pd.set_option("precision", 5) # display precision in terms of decimal places
#pd.set_option("expand_frame_repr", True)
#pd.set_option("chop_threshold", 0) # what level pandas rounds to zero when it displays a Series
------------------

----- stdout -----
Display Rows: 60
Display Columns: 20
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOptionError[0m                               Traceback (most recent call last)
Cell [0;32mIn[49], line 3[0m
[1;32m      1[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mDisplay Rows:[39m[38;5;124m"[39m,pd[38;5;241m.[39mget_option([38;5;124m"[39m[38;5;124mdisplay.max_rows[39m[38;5;124m"[39m))
[1;32m      2[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mDisplay Columns:[39m[38;5;124m"[39m,pd[38;5;241m.[39mget_option([38;5;124m"[39m[38;5;124mdisplay.max_columns[39m[38;5;124m"[39m))
[0;32m----> 3[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mDisplay Precision:[39m[38;5;124m"[39m,[43mpd[49m[38;5;241;43m.[39;49m[43mget_option[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mprecision[39;49m[38;5;124;43m"[39;49m[43m)[49m)
[1;32m      4[0m [38;5;66;03m#pd.set_option("display.max_rows", 5)[39;00m
[1;32m      5[0m [38;5;66;03m#pd.set_option("display.max_columns", 5)[39;00m
[1;32m      6[0m [38;5;66;03m#pd.set_option("precision", 5) # display precision in terms of decimal places[39;00m
[1;32m      7[0m [38;5;66;03m#pd.set_option("expand_frame_repr", True)[39;00m
[1;32m      8[0m [38;5;66;03m#pd.set_option("chop_threshold", 0) # what level pandas rounds to zero when it displays a Series[39;00m

File [0;32m~/miniconda3/envs/py311/lib/python3.11/site-packages/pandas/_config/config.py:274[0m, in [0;36mCallableDynamicDoc.__call__[0;34m(self, *args, **kwds)[0m
[1;32m    273[0m [38;5;28;01mdef[39;00m [38;5;21m__call__[39m([38;5;28mself[39m, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds) [38;5;241m-[39m[38;5;241m>[39m T:
[0;32m--> 274[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[38;5;18;43m__func__[39;49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m

File [0;32m~/miniconda3/envs/py311/lib/python3.11/site-packages/pandas/_config/config.py:146[0m, in [0;36m_get_option[0;34m(pat, silent)[0m
[1;32m    145[0m [38;5;28;01mdef[39;00m [38;5;21m_get_option[39m(pat: [38;5;28mstr[39m, silent: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mFalse[39;00m) [38;5;241m-[39m[38;5;241m>[39m Any:
[0;32m--> 146[0m     key [38;5;241m=[39m [43m_get_single_key[49m[43m([49m[43mpat[49m[43m,[49m[43m [49m[43msilent[49m[43m)[49m
[1;32m    148[0m     [38;5;66;03m# walk the nested dict[39;00m
[1;32m    149[0m     root, k [38;5;241m=[39m _get_root(key)

File [0;32m~/miniconda3/envs/py311/lib/python3.11/site-packages/pandas/_config/config.py:134[0m, in [0;36m_get_single_key[0;34m(pat, silent)[0m
[1;32m    132[0m     [38;5;28;01mraise[39;00m OptionError([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNo such keys(s): [39m[38;5;132;01m{[39;00m[38;5;28mrepr[39m(pat)[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m    133[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(keys) [38;5;241m>[39m [38;5;241m1[39m:
[0;32m--> 134[0m     [38;5;28;01mraise[39;00m OptionError([38;5;124m"[39m[38;5;124mPattern matched multiple keys[39m[38;5;124m"[39m)
[1;32m    135[0m key [38;5;241m=[39m keys[[38;5;241m0[39m]
[1;32m    137[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m silent:

[0;31mOptionError[0m: Pattern matched multiple keys

